### ISSUE TITLE
Implement of DataSource Class for Loading Hotel Graph

### ISSUE THREAD

**Issue by VesnaVasic** [anapoparic/DataGraphVisualization#13]
**Description**:
Implement the **DataSource** class to load data about hotels, cities and countries using RapidAPI endpoints. The class will utilize functions to load  hotels, cities and countries, add nodes and edges to the graph. This will enable the creation of a graph representing hotels, cities , and their connections.

**Tasks**:
- [x] Define the **load method:**
Implement the load method which takes a configuration as input and returns a hotel graph using the load_graph function.
- [x] Define the **identifier method:**
Implement the identifier method to return a unique identifier for this data source.
- [x]  Define the **name method:**
Implement the name method to return the name of the data source.
- [x]  Define the **config method:**
Implement the config method to return the configuration options for this data source.
